### ISSUE TITLE
App is unusable in landscape orientation

### ISSUE THREAD

**Issue by kriticalflare** [skydoves/MarvelHeroes#1]
- App Version - 1.0.0.Release from https://github.com/skydoves/MarvelHeroes/releases/download/1.0.0/app-debug.apk
- Affected Device(s) Asus X01BD
 
**Describe the Bug:**

Unable to scroll in the heroes' detail pages.

**Expected Behavior:**

App to adapt to landscape orientation and display the content properly

Attached gif of the app in landscape
 <img src="https://user-images.githubusercontent.com/42350771/77446311-438df700-6e14-11ea-973a-38cbcd030d63.gif" width="420" height="720">

**Comment by skydoves** [comment]
Hi, thank you for your issue. :)
It should be supported only `portrait`. I will fix it and upload it again now!

**Comment by skydoves** [comment]
It has just been updated.
Thank you for your issue 👍
