### ISSUE TITLE
How isLoading works?

### ISSUE THREAD

**Issue by abalta** [skydoves/MarvelHeroes#2]
Hi, thank you for this modern repository. However, I did not get any usage of isLoading value. How can I use it?

**Comment by abalta** [comment]
Ok, I got it. I use like toast message like below.

This is my repository.

`
suspend fun getGoal(isLoading: (Boolean) -> Unit)
`

In my viewmodel I use like this.
```

    init {
        goalsLiveData = fetchGoalsLiveData.switchMap {
            launchOnViewModelScope {
                onboardingRepository.getGoal {
                    showProgressVisibleMutableLiveData.postValue(it)
                }
            }
        }
    }
```

**Comment by skydoves** [comment]
Good :) Actually the loading property does not need in this repository.
I was thinking It needs paging, but this project loads only a few responses.
