### ISSUE TITLE
When i clone repository cannot create new datasource instance always take old data

### ISSUE THREAD

**Issue by rickymerby** [skydoves/MarvelHeroes#4]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hi, @rickymerby!
Could you explain more details about this issue?
You should not reuse the same instance of `DataSource` in different repositories.
And you can reference the [Sandwich](https://github.com/skydoves/sandwich) library for using the `DataSource` better.
